image: debian:11

build:
  before_script:
    - apt-get update && apt-get install -y curl git
    - export VOLTA_HOME=/root/.volta
    - export PATH=$VOLTA_HOME/bin:$PATH
    - curl https://get.volta.sh | bash -s -- --skip-setup
  script:
    - yarn install --immutable
    - yarn build

include:
  - template: SAST.gitlab-ci.yml


