services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dev
  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    # allow access to host's localhost from within the container
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ${PWD}/prometheus-mock-config.yaml:/prometheus.yml
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
