apiVersion: batch/v1
kind: CronJob
metadata:
  name: churros-housekeeping
spec:
  # run monthly at some low-traffic time
  schedule: '7 4 2 * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hello
              image: curlimages/curl:latest
              env:
                - name: USERS_THRESHOLD
                  value: 1825 # = 365 * 5 days
                - name: EVENTS_THRESHOLD
                  value: 365 # days
                - name: NOTIFS_THRESHOLD
                  value: 30 # days
                - name: LOGS_THRESHOLD
                  value: 90 # days
                - name: GDPR_EXPORTS_THRESHOLD
                  value: 30 # days
              envFrom:
                - configMapRef:
                    name: churros-config
                - secretRef:
                    name: churros-secrets
              # call graphql mutation Mutation.housekeep
              command:
                - '-X'
                - 'POST'
                - '-H'
                - 'Content-Type: application/json'
                - '-d'
                - >
                  {
                    "query":"
                      mutation RunHousekeeper($token: String!) { 
                        housekeep(token: $token, thresholds: { 
                          eventEndedAt: $EVENTS_THRESHOLD, 
                          userLastLogin: $USERS_THRESHOLD,
                          logHappenedAt: $LOGS_THRESHOLD,
                          notificationSentAt: $NOTIFS_THRESHOLD,
                          gdprExportCreatedAt: $GDPR_EXPORTS_THRESHOLD,
                        }) { 
                          __typename 
                          ...on Error { message } 
                          ...on HousekeepingResult {
                            deletedEvents
                            deletedUsers
                            deletedLogs
                            deletedGdprExports
                            warnedUsers
                            deletedNotifications
                            deletedAppleWalletFiles
                          }
                        } 
                      }
                    ", 
                    "operationName":"RunHousekeeper", 
                    "variables": { "token": "$HOUSEKEEPER_TOKEN" }
                  }
                - 'http://churros-api:4000/graphql'
