apiVersion: batch/v1
kind: CronJob
metadata:
  name: churros-housekeeping
spec:
  # run monthly at some low-traffic time
  schedule: '7 4 2 * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hello
              image: curlimages/curl:latest
              env:
                - name: USERS_THRESHOLD
                  value: 1825 # = 365 * 5 days
                - name: EVENTS_THRESHOLD
                  value: 365 # days
              envFrom:
                - configMapRef:
                    name: churros-config
                - secretRef:
                    name: churros-secrets
              # call graphql mutation Mutation.housekeep
              command:
                - '-X'
                - 'POST'
                - '-H'
                - 'Content-Type: application/json'
                - '-d'
                - '{"query":"mutation RunHousekeeper($token: String!, $events: Int!, $users: Int!) { housekeep(token: $token, expiredEventsDaysThreshold: $events, expiredUsersDaysThreshold: $users) { __typename ...on Error {message} } }", "operationName":"RunHousekeeper", "variables": {"token": "$HOUSEKEEPER_TOKEN", "events": $EVENTS_THRESHOLD, "users": $USERS_THRESHOLD}}'
                - 'http://churros-api:4000/graphql'
