apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: centraverse-api-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: centraverse-repository-api
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: centraverse-app-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: centraverse-repository-app
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: centraverse-sync-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: centraverse-repository-sync
  policy:
    semver:
      range: '>=1.0.0'
