apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: centraverse-prod
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: centraverse
      owner: centraverse
  storage:
    size: 15Gi
    storageClass: local-ssd
  monitoring:
    enablePodMonitor: true
  backup:
    barmanObjectStore:
      destinationPath: s3://data/barman/centraverse
      endpointURL: http://hubble.inpt.fr:9000
      s3Credentials:
        accessKeyId:
          name: s3-pg-backup
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: s3-pg-backup
          key: AWS_SECRET_ACCESS_KEY
    retentionPolicy: 30d
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: centraverse-daily
  namespace: centraverse-prod
spec:
  schedule: '0 40 2 * * *'
  backupOwnerReference: self
  cluster:
    name: postgresql
