apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centraverse-data
  namespace: centraverse-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
