.changesets:
  image: debian:12
  before_script:
    - apt-get update && apt-get install -y curl git jq moreutils
    - export VOLTA_HOME=/root/.volta
    - export PATH=$VOLTA_HOME/bin:$PATH
    - curl https://get.volta.sh | bash -s -- --skip-setup
    - yarn config set enableGlobalCache false
    - yarn config set enableImmutableInstalls true
    - yarn install
    - export GITLAB_TOKEN=$CHANGESETS_TOKEN
    - |
      cat << EOF > "$HOME/.npmrc"
        email=$NPM_EMAIL
        //registry.npmjs.org/:_authToken=$NPM_TOKEN
      EOF
  cache:
    paths:
      - .yarn/cache/

comment:
  extends: .changesets
  stage: changesets
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - yarn changesets-gitlab comment

release:
  extends: .changesets
  stage: changesets
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    INPUT_TITLE: 'chore: version packages'
    INPUT_COMMIT: 'chore: version packages'
    YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'
    INPUT_VERSION: 'yarn update-versions'
    INPUT_PUBLISH: 'yarn changeset tag'
  script:
    - yarn changesets-gitlab
