.kaniko:
  image:
    name: gcr.io/kaniko-project/executor:v1.21.1-debug
    entrypoint: ['']
  before_script:
    - echo $HARBOR_CONFIG_JSON
    - cp $HARBOR_CONFIG_JSON /kaniko/.docker/config.json

deploy:
  extends: .kaniko
  stage: deploy
  needs:
    - build

  only:
    - tags
  script:
    - /kaniko/executor
      --cache=true
      --use-new-run
      --snapshot-mode=redo
      --cache-copy-layers
      --cache-run-layers
      --skip-unused-stages
      --cache-repo="$HARBOR_REGISTRY_IMAGE/cache"
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/Dockerfile"
      --target "api"
      --destination "$HARBOR_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA"
    - /kaniko/executor
      --cache=true
      --use-new-run
      --snapshot-mode=redo
      --cache-copy-layers
      --cache-run-layers
      --skip-unused-stages
      --cache-repo="$HARBOR_REGISTRY_IMAGE/cache"
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/Dockerfile"
      --target "app"
      --destination "$HARBOR_REGISTRY_IMAGE/app:$CI_COMMIT_SHORT_SHA"
