.buildkit:
  image:
    name: moby/buildkit:rootless
    entrypoint: ['sh', '-c']
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - mkdir ~/.docker
    - cp $HARBOR_CONFIG_JSON ~/.docker/config.json

deploy_prisma:
  extends: .buildkit
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^@churros\/db@(\d+\.\d+\.\d+)/
  script:
    - export TAG=$(echo $CI_COMMIT_TAG | sed 's/@churros\/db@//')
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=prisma \
          --opt build-arg:TAG=$TAG \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/prisma:v$TAG,push=true
    - echo "Successfully built and pushed $HARBOR_REGISTRY_IMAGE/prisma:v$TAG"

deploy_api:
  extends: .buildkit
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^@churros\/api@(\d+\.\d+\.\d+)/
    - when: manual
  script:
    - export TAG=$(echo $CI_COMMIT_TAG | sed 's/@churros\/api@//')
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=api \
          --secret id=SENTRY_AUTH_TOKEN \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/api:v$TAG,push=true
    - echo "Successfully built and pushed $HARBOR_REGISTRY_IMAGE/api:v$TAG"

deploy_app:
  extends: .buildkit
  stage: deploy
  variables:
    SENTRY_PROJECT: app
  rules:
    - if: $CI_COMMIT_TAG =~ /^@churros\/app@(\d+\.\d+\.\d+)/
    - when: manual
  script:
    - export TAG=$(echo $CI_COMMIT_TAG | sed 's/@churros\/app@//')
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=app \
          --opt build-arg:TAG=$TAG \
          --secret id=SENTRY_AUTH_TOKEN \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/app:v$TAG,push=true
    - echo "Successfully built and pushed $HARBOR_REGISTRY_IMAGE/app:v$TAG"

deploy_sync:
  extends: .buildkit
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^@churros\/sync@(\d+\.\d+\.\d+)/
    - when: manual
  script:
    - export TAG=$(echo $CI_COMMIT_TAG | sed 's/@churros\/sync@//')
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=sync \
          --opt build-arg:TAG=$TAG \
          --secret id=SENTRY_AUTH_TOKEN \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/sync:v$TAG,push=true
    - echo "Successfully built and pushed $HARBOR_REGISTRY_IMAGE/sync:v$TAG"
