.buildkit:
  image:
    name: moby/buildkit:rootless
    entrypoint: ['sh', '-c']
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - mkdir ~/.docker
    - cp $HARBOR_CONFIG_JSON ~/.docker/config.json

deploy_prisma:
  extends: .buildkit
  stage: deploy
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^@churros\/db@(\d+\.\d+\.\d+)/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    # $TAG or $CI_COMMIT_TAG
    - if [ -z "$TAG" ]; then TAG=$(echo $CI_COMMIT_TAG | sed 's/@churros\/db@//'); fi
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=sync \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/sync:v$TAG,push=true

deploy_api:
  extends: .buildkit
  stage: deploy
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^@churros\/api@(\d+\.\d+\.\d+)/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - if [ -z "$TAG" ]; then TAG=$(echo $CI_COMMIT_TAG | sed 's/@churros\/api@//'); fi
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=api \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/api:v$TAG,push=true

deploy_app:
  extends: .buildkit
  stage: deploy
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^@churros\/app@(\d+\.\d+\.\d+)/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - if [ -z "$TAG" ]; then TAG=$(echo $CI_COMMIT_TAG | sed 's/@churros\/app@//'); fi
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=app \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/app:v$TAG,push=true

deploy_sync:
  extends: .buildkit
  stage: deploy
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^@churros\/sync@(\d+\.\d+\.\d+)/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - if [ -z "$TAG" ]; then TAG=$(echo $CI_COMMIT_TAG | sed 's/@churros\/sync@//'); fi
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=sync \
          --output type=image,name=$HARBOR_REGISTRY_IMAGE/sync:v$TAG,push=true
