apiVersion: batch/v1
kind: CronJob
metadata:
  name: churros-sync
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: harbor.k8s.inpt.fr/net7/centraverse/sync:latest
              imagePullPolicy: Always
              env:
                - name: DATABASE_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-app
                      key: uri
                - name: DATABASE_URL
                  value: $(DATABASE_BASE_URL)?pool_timeout=60
          restartPolicy: Never
