name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    steps:
      - uses: actions/checkout@v2
      - name: Setup Volta
        run: |
          sudo apt-get update && sudo apt-get install -y curl git jq moreutils
          export VOLTA_HOME=/root/.volta
          export PATH=$VOLTA_HOME/bin:$PATH
          curl https://get.volta.sh | bash -s -- --skip-setup
          echo 'export VOLTA_HOME=/root/.volta' >> $GITHUB_ENV
          echo 'export PATH=$VOLTA_HOME/bin:$PATH' >> $GITHUB_ENV
      - name: Install Yarn
        run: |
          yarn config set enableGlobalCache false
          yarn config set enableImmutableInstalls true
          yarn install
      - name: Build
        run: yarn build
        if: github.event.pull_request.draft == false || github.event_name == 'push'
